# Predict labels for Issues using a trained model
name: "Labeler: Predict (Issues)"

on:
  # Only automatically predict area labels when issues are first opened
  issues:
    types: [opened]

  # Allow dispatching the workflow via the Actions UI, specifying ranges of numbers
  workflow_dispatch:
    inputs:
      issues:
        description: "Issue Numbers (comma-separated list of ranges)."
        required: true
      dry_run:
        description: "Run in dry-run mode for manual dispatches. Defaults to 'false'."
        required: false
        type: boolean
        default: false
      cache_key:
        description: "The cache key suffix to use for restoring the model. Defaults to 'ACTIVE'."
        required: true
        default: "ACTIVE"

permissions: {}

env:
  ALLOW_FAILURE: ${{ github.event_name != 'workflow_dispatch' }}
  LABEL_PREFIX: "area-"
  THRESHOLD: ${{ vars.ISSUE_LABELER_PREDICTION_THRESHOLD_ISSUES || vars.ISSUE_LABELER_PREDICTION_THRESHOLD || '0.15' }}
  DEFAULT_LABEL: "needs-area-label"
  MAX_LABELS: ${{ vars.ISSUE_LABELER_MAX_LABELS_ISSUES || vars.ISSUE_LABELER_MAX_LABELS || '1' }}

jobs:
  predict-issue-label:
    # Do not automatically run on forked repositories
    if: ${{ github.event_name == 'workflow_dispatch' || !github.event.repository.fork }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Restore issues model from cache"
        id: restore-model
        uses: dotnet/issue-labeler/restore@98f1d9b85686147ffdc155547cdd3469546c4e26 # v2.1.0
        with:
          type: issues
          fail-on-cache-miss: ${{ !fromJSON(env.ALLOW_FAILURE) }}
          quiet: true
          cache_key: ${{ github.event.inputs.cache_key || 'ACTIVE' }}

      - name: "Predict issue labels"
        id: prediction
        if: ${{ steps.restore-model.outputs.cache-hit == 'true' }}
        uses: dotnet/issue-labeler/predict@98f1d9b85686147ffdc155547cdd3469546c4e26 # v2.1.0
        with:
          issues: ${{ github.event.inputs.issues || github.event.issue.number }}
          label_prefix: ${{ env.LABEL_PREFIX }}
          threshold: ${{ env.THRESHOLD }}
          default_label: ${{ env.DEFAULT_LABEL }}
          dry_run: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run || 'false' }}
          max_labels: ${{ env.MAX_LABELS }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        continue-on-error: ${{ fromJSON(env.ALLOW_FAILURE) }}
