# Predict labels for Discussions using a trained model
name: "Labeler: Predict (Discussions)"

on:
  # Only automatically predict area labels when discussions are first created
  discussion:
    types: [created]

  # Allow dispatching the workflow via the Actions UI, specifying ranges of numbers
  workflow_dispatch:
    inputs:
      discussions:
        description: "Discussion Numbers (comma-separated list of ranges)."
        required: true
      dry_run:
        description: "Run in dry-run mode for manual dispatches. Defaults to 'true'."
        required: false
        default: "true"
      cache_key:
        description: "The cache key suffix to use for restoring the model. Defaults to 'ACTIVE'."
        required: true
        default: "ACTIVE"

env:
  ALLOW_FAILURE: ${{ github.event_name != 'workflow_dispatch' }}
  LABEL_PREFIX: "area-"
  THRESHOLD: 0.40
  DEFAULT_LABEL: "needs-area-label"

jobs:
  predict-discussion-label:
    # Do not automatically run on forked repositories
    if: ${{ github.event_name == 'workflow_dispatch' || !github.event.repository.fork }}
    runs-on: ubuntu-latest
    permissions:
      discussions: write
      issues: write
    steps:
      - name: "Restore discussions model from cache"
        id: restore-model
        uses: dotnet/issue-labeler/restore@main
        with:
          type: discussions
          fail-on-cache-miss: ${{ !fromJSON(env.ALLOW_FAILURE) }}
          quiet: true
          cache_key: ${{ github.event.inputs.cache_key || 'ACTIVE' }}

      - name: "Predict discussion labels"
        if: ${{ steps.restore-model.outputs.cache-hit == 'true' }}
        uses: dotnet/issue-labeler/predict@main
        with:
          discussions: ${{ github.event.inputs.discussions || github.event.discussion.number }}
          label_prefix: ${{ env.LABEL_PREFIX }}
          threshold: ${{ env.THRESHOLD }}
          default_label: ${{ env.DEFAULT_LABEL }}
          dry_run: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run || 'false' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          INPUT_ISSUES_MODEL: labeler-cache/discussions-model.zip
        continue-on-error: ${{ fromJSON(env.ALLOW_FAILURE) }}