# Predict labels for Pull Requests using a trained model
name: "Labeler: Predict (Pulls)"

on:
  # Per to the following documentation:
  # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target
  #
  # The `pull_request_target` event runs in the context of the base of the pull request, rather
  # than in the context of the merge commit, as the `pull_request` event does. This prevents
  # execution of unsafe code from the head of the pull request that could alter the repository
  # or steal any secrets you use in your workflow. This event allows your workflow to do things
  # like label or comment on pull requests from forks.
  #
  # Only automatically predict area labels when pull requests are first opened
  pull_request_target:
    types: opened

  # Allow dispatching the workflow via the Actions UI, specifying ranges of numbers
  workflow_dispatch:
    inputs:
      pulls:
        description: "Pull Request Numbers (comma-separated list of ranges)."
        required: true
      dry_run:
        description: "Run in dry-run mode for manual dispatches. Defaults to 'false'."
        required: false
        type: boolean
        default: false
      cache_key:
        description: "The cache key suffix to use for restoring the model. Defaults to 'ACTIVE'."
        required: true
        default: "ACTIVE"

permissions: {}

env:
  # Suppress failures on automatic runs to avoid blocking PR merges; surface failures on manual dispatch
  ALLOW_FAILURE: ${{ github.event_name != 'workflow_dispatch' }}

  LABEL_PREFIX: "area-"
  THRESHOLD: ${{ vars.ISSUE_LABELER_PREDICTION_THRESHOLD_PULLS || vars.ISSUE_LABELER_PREDICTION_THRESHOLD || '0.40' }}
  DEFAULT_LABEL: "needs-area-label"
  MAX_LABELS: ${{ vars.ISSUE_LABELER_MAX_LABELS_PULLS || vars.ISSUE_LABELER_MAX_LABELS || '1' }}

jobs:
  predict-pull-label:
    # Do not automatically run the workflow on forked repositories
    if: ${{ github.event_name == 'workflow_dispatch' || !github.event.repository.fork }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: "Restore pulls model from cache"
        id: restore-model
        uses: dotnet/issue-labeler/restore@00ce11f3eef738334ec9092ead6e5f34db9218a4 # v2.1.0
        with:
          type: pulls
          fail-on-cache-miss: ${{ !fromJSON(env.ALLOW_FAILURE) }}
          quiet: true
          cache_key: ${{ github.event.inputs.cache_key || 'ACTIVE' }}

      - name: "Predict pull labels"
        id: prediction
        if: ${{ steps.restore-model.outputs.cache-hit == 'true' }}
        uses: dotnet/issue-labeler/predict@00ce11f3eef738334ec9092ead6e5f34db9218a4 # v2.1.0
        with:
          pulls: ${{ github.event.inputs.pulls || github.event.number }}
          label_prefix: ${{ env.LABEL_PREFIX }}
          threshold: ${{ env.THRESHOLD }}
          default_label: ${{ env.DEFAULT_LABEL }}
          dry_run: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run || 'false' }}
          max_labels: ${{ env.MAX_LABELS }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        continue-on-error: ${{ fromJSON(env.ALLOW_FAILURE) }}
