# Promote a model from staging to 'ACTIVE', backing up the currently 'ACTIVE' model
name: "Labeler: Promotion"

on:
  # Dispatched via the Actions UI, promotes the staged models from
  # a staged slot into the prediction environment
  workflow_dispatch:
    inputs:
      issues:
        description: "Issues: Promote Model"
        type: boolean
        required: true
      pulls:
        description: "Pulls: Promote Model"
        type: boolean
        required: true
      discussions:
        description: "Discussions: Promote Model"
        type: boolean
        required: true
      staged_key:
        description: "The cache key suffix to use for promoting a staged model to 'ACTIVE'. Defaults to 'staged'."
        required: true
        default: "staged"
      backup_key:
        description: "The cache key suffix to use for backing up the currently active model. Defaults to 'backup'."
        required: false
        default: "backup"

permissions: {}

jobs:
  promote-issues:
    if: ${{ github.event.inputs.issues == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: "Promote Model for Issues"
        uses: dotnet/issue-labeler/promote@00ce11f3eef738334ec9092ead6e5f34db9218a4 # v2.1.0
        with:
          type: "issues"
          staged_key: ${{ github.event.inputs.staged_key }}
          backup_key: ${{ github.event.inputs.backup_key }}

  promote-pulls:
    if: ${{ github.event.inputs.pulls == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: "Promote Model for Pull Requests"
        uses: dotnet/issue-labeler/promote@00ce11f3eef738334ec9092ead6e5f34db9218a4 # v2.1.0
        with:
          type: "pulls"
          staged_key: ${{ github.event.inputs.staged_key }}
          backup_key: ${{ github.event.inputs.backup_key }}

  promote-discussions:
    if: ${{ github.event.inputs.discussions == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: "Promote Model for Discussions"
        uses: dotnet/issue-labeler/promote@00ce11f3eef738334ec9092ead6e5f34db9218a4 # v2.1.0
        with:
          type: "discussions"
          staged_key: ${{ github.event.inputs.staged_key }}
          backup_key: ${{ github.event.inputs.backup_key }}
