# Predict labels for Issues and Discussions using a trained model
name: "Labeler: Predict (Issues & Discussions)"

on:
  # Only automatically predict area labels when issues are first opened
  issues:
    types: [opened]
  discussion:
    types: [created]

  # Allow dispatching the workflow via the Actions UI, specifying ranges of numbers
  workflow_dispatch:
    inputs:
      issues:
        description: "Issue Numbers (comma-separated list of ranges)."
        required: true
      cache_key:
        description: "The cache key suffix to use for restoring the model. Defaults to 'ACTIVE'."
        required: true
        default: "ACTIVE"

env:
  LABEL_PREFIX: "area-"
  THRESHOLD: 0.40
  DEFAULT_LABEL: "needs-area-label"

jobs:
  predict-issue-label:
    # Do not automatically run on discussion events or on forks outside the 'dotnet' org
    if: ${{ github.event_name != 'discussion' && (github.event_name == 'workflow_dispatch' || github.repository_owner == 'dotnet') }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Restore issues model from cache"
        id: restore-model
        uses: dotnet/issue-labeler/restore@main
        with:
          type: issues
          fail-on-cache-miss: ${{ github.event_name == 'workflow_dispatch' }}
          quiet: true
          cache_key: ${{ inputs.cache_key || 'ACTIVE' }}

      - name: "Predict issue labels"
        id: prediction
        if: ${{ steps.restore-model.outputs.cache-hit == 'true' }}
        uses: dotnet/issue-labeler/predict@main
        with:
          issues: ${{ inputs.issues || github.event.issue.number }}
          pulls: ""
          label_prefix: ${{ env.LABEL_PREFIX }}
          threshold: ${{ env.THRESHOLD }}
          default_label: ${{ env.DEFAULT_LABEL }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        continue-on-error: ${{ github.event_name != 'workflow_dispatch' }}

  label-discussion:
    # Only run on discussion events, and only on the 'dotnet' org (not forks)
    if: ${{ github.event_name == 'discussion' && github.repository_owner == 'dotnet' }}
    runs-on: ubuntu-latest
    permissions:
      discussions: write
      issues: write
    steps:
      - name: "Restore issues model from cache"
        id: restore-model
        uses: dotnet/issue-labeler/restore@main
        with:
          type: issues
          fail-on-cache-miss: false
          quiet: true
          cache_key: 'ACTIVE'

      - name: "Predict discussion labels"
        if: ${{ steps.restore-model.outputs.cache-hit == 'true' }}
        uses: dotnet/issue-labeler/predict@main
        with:
          discussions: ${{ github.event.discussion.number }}
          label_prefix: ${{ env.LABEL_PREFIX }}
          threshold: ${{ env.THRESHOLD }}
          default_label: ${{ env.DEFAULT_LABEL }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        continue-on-error: true
